print("Hello World from Python")
a = input("What is your name? ")
print("My name is {}".format(a))
b = input("What do you do for fun?")
print("So your hobbies are {}".format(b))
c = input("What is your university name? ")
print("So your university name is {}".format(c))
